// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "151a6847-0850-47ae-a59c-0af06065e56d";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onSchedulerChange();

int category;
int clarityLevel;
int clarityN;
int clarityP;
int healthLevel;
int healthN;
int healthP;
int mentalityLevel;
int mentalityN;
int mentalityP;
int privateLevel;
int privateN;
int privateP;
int responsibilityLevel;
int responsibilityN;
int responsibilityP;
int stressLevel;
int vote;
int votedN;
int votedP;
int workloadLevel;
int workloadN;
int workloadP;
CloudSchedule scheduler;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(category, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(clarityLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(clarityN, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(clarityP, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(healthLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(healthN, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(healthP, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(mentalityLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(mentalityN, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(mentalityP, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(privateLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(privateN, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(privateP, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(responsibilityLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(responsibilityN, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(responsibilityP, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(stressLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vote, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(votedN, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(votedP, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(workloadLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(workloadN, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(workloadP, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(scheduler, READWRITE, ON_CHANGE, onSchedulerChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
